server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  # Corregido: defaultZone en lugar de default-zone

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/car/**

        - id: USUARIO-SERVICE  # He cambiado el identificador a mayúsculas
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
