server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      instance:
        hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/car/**

        - id: USUARIO-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
