server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/ar316/microservicio
          search-paths: config-data
